### ISSUE TITLE
Only the first part of the sequence seem to be analyzed

### ISSUE THREAD

**Issue by Ilarius** [fmicompbio/mutscan#42]
Hello,
I have PE fastq where a protein of 412 aa has been mutagenized. Each event involves in theory only 1 aa. More than 200 sites have been invididually mutated in each sites.
When I use you digestFastqs() function however, I can only find a few events with only 1 aa mutated and with very low frequency, most of the ones found have more than 50 changes. The quality of the sequencing is very high (30 or more).
Aother weird  behavior is that it only finds mutations in the first 51 of the 412 sites. It seems like it only searches for overlaps on the first portion of the wild type sequence. This does not happen if I do not provide the wild type sequence.
Is there something I am missing?

Here is the code of my call:

`
out1b <- digestFastqs(
  fastqForward = "R.fq.gz",
  fastqReverse = "L.fq.gz",
  mergeForwardReverse = TRUE, revComplForward = FALSE, revComplReverse = TRUE, minOverlap=15, maxOverlap = 300,greedyOverlap=FALSE,variableCollapseMinReads = 10**100,
  elementsForward = "V", 
  elementsReverse = "V", elementLengthsForward=-1, elementLengthsReverse=-1,
  wildTypeForward = alac,#sequence of 1239 nt
  nbrMutatedCodonsMaxReverse=-1, nThreads=10,
  variableNMaxForward=1, 
  nbrMutatedCodonsMaxForward=1# 258 retained reads with this parameter, becomes over 2 millions if I use a very high number
  )
`

**Comment by csoneson** [comment]
Hi @Ilarius - a couple of questions to understand your setup and the potential issue better: 

- How long are your reads? Do they cover the full WT sequence after merging of the forward and reverse reads? And does the first base in the forward read always correspond to the first base in the WT sequence? 
- If you don't provide the WT sequence, how long are the variable regions you get out from `digestFastqs()`?

**Comment by Ilarius** [comment]
Hi!
Thanks for the fast answer.
My reads are 2x151 and yes they have a good coverage (minimum 30k for each bases of the WT sequence). My reads span the whole WT sequence but it looks like if I select only the reads with 1 mutated aa (that are the ones that in theory I should get for a total of 6740 possible variants: 337/312 mutagenized sites per 20aa) I only find 16 sequences and they all started with the initial ATG.

If I do not provide de WT sequenes the varLengths are from 35 to 259 (median 151=read length)

**Comment by csoneson** [comment]
Ah yes, this is the issue - `mutscan` assumes that the extracted variable sequence starts at the beginning of the provided WT sequence (we may need to make this clearer in the docs). You can kind of work around it by creating a vector of WT sequences, each consisting of a truncated version of the full WT sequence, successively excluding the first k bases (k=1,2,3,...). Not perfect, as it won't keep track of where the codons actually start and end. However, it will give you a count of each variant, regardless of where it starts (`mutscan` will find the closest wildtype sequence). Generally, the main difficulty in such a setup though is that you don't really know what happens outside of the sequenced region - the molecule that the sequenced fragment comes from could have additional mutations outside of what you see.

**Comment by Ilarius** [comment]
Hello! I understand.
So I was trying to do a small trial using a sequence starting at the first codon (ATG), sequenceA,  and the same sequence starting at the second codon, sequence B) for then looking at the detected vartiant of the second codon:

a mutation of the second triplet GCG --> CAC was detected in both cases.
But I struggle understanding the total number of reads supporting for that variant:

sequence A: 180 reads

Sequenza B: 20 reads
How coudl it be that removing the initial ATG (first triplet) I only detect 20 supporting reads?
In theory I should find also all 180 that I found with the complete sequence, shouldn't I?

**Comment by Ilarius** [comment]
Yes exactly. The two sequences only differ for the wild type sequence, in the first it starts with the ATG, and the second start with the second codon

**Comment by csoneson** [comment]
Hi @Ilarius - just wanted to check in to see whether the issue was resolved (at least to the extent of what `mutscan` is able to provide at the moment), or if there's still something that we should clarify.

**Comment by Ilarius** [comment]
Hello, thanks for following up. In the end I opted per manually blasting my reads on the wild type sequence and counting the frequency of each triplet in each position. In this way I am getting more hits compared to what I was able to get by using mutscan.

**Comment by csoneson** [comment]
Yes, I think that is sensible - I'll close this issue then!
