### ISSUE TITLE
Issue using reference sequence in digestFastqs and error creating QC report

### ISSUE THREAD

**Issue by shesanIsland** [fmicompbio/mutscan#46]
Hi,

Before starting thank you for creating a very useful package! I am currently using _mutscan_ to analyse deep mutational scanning data of selected and unselected amplicon samples. The group is hoping to look at single and double amino acid mutations.

**First issue:** 
Using `digestFastqs`, whenever I add the WT seq for that gene (currently unsure what/if variable or constant regions), I get 0% retained reads despite checking that (parts of the) reads can be found in the WT. Without the reference, around 98% of reads are retained.

Looking at the filtering stage, it looks like  step10 is the issue however even if `nbrMutatedCodonsMaxForward` or `nbrMutatedBasesMaxForward` is set to `Inf` or a high number, reads retained remains at 0%.

Command (NB some args are written, but not passed):
```
sample_S1 <- digestFastqs(
    fastqForward = file.path(sampledir, "S1_merged.fastq.gz"),
    fastqReverse = NULL,
    mergeForwardReverse = FALSE,
    #minOverlap = 0, 
    #maxOverlap = Inf,
    revComplForward = FALSE, 
    revComplReverse = TRUE,
    elementsForward = "V", 
    elementLengthsForward = -1, 
    elementsReverse = "V",
    elementLengthsReverse = -1,
    avePhredMinForward = 30,
    avePhredMinReverse = 30,
    variableNMaxForward = 15, 
    variableNMaxReverse = 0,
    umiNMax = 0,
    wildTypeForward = c(H1A1 = WTref),       # 'WTref' seq saved as variable
    nbrMutatedCodonsMaxForward = 4, 
    #nbrMutatedCodonsMaxReverse = 1,
    #nbrMutatedBasesMaxForward = -1,
    #nbrMutatedBasesMaxReverse = -1,
    constantMaxDistForward = -1, 
    constantMaxDistReverse = -1,
    mutatedPhredMinForward = 0,
    mutatedPhredMinReverse = 0,
    verbose = TRUE)
```

**Second issue:**
I am having trouble creating the QC file in JupyterLab, initially fine with `se` test data but doesn't work w my summarizedExperiment object, `aa_collapse02`. I have tried to create the report in a new document but unable to.
Command:
```
generateQCReport(aa_collapse02,
                 outFile = tempfile(fileext = ".html"),
                 reportTitle = "mutscan QC report for DMS",
                 forceOverwrite = TRUE,
                 output_file = "PATHNAME/results/QCresults_S1-S5.html"
                )
```

Error:
```
Warning message in generateQCReport(aa_collapse02, outFile = tempfile(fileext = ".html"), :
“Will ignore arguments provided in '...' that are set internally by generateQCReport: output_file”
Error: Failed to run 'rmarkdown::render' in a new R session.
Traceback:
1. generateQCReport(aa_collapse02, outFile = tempfile(fileext = ".html"), 
 .     reportTitle = "mutscan QC report for DMS", forceOverwrite = TRUE, 
 .     output_file = "PATHNAME/results/QCresults_S1-S5.html")
2. xfun::Rscript_call(rmarkdown::render, args)
3. stop(fail, call. = FALSE)
```

If useful, I am using JupyterLab via GoogleCloud's Vertex platform.
Much appreciated.

**Comment by csoneson** [comment]
Hi @shesanIsland - thanks for using `mutscan`! 

**First issue**
Could you provide a bit more context about your read composition (you say that "(parts of the) reads can be found in the WT" - are these matches always in the same part of the reads?) Currently, `mutscan` assumes that the beginning of the extracted variable region aligns with the start of the provided wildtype sequence. Thus, you need to tell `digestFastqs()` from where in the read it should extract the variable region (either a fixed position, or following a given primer sequence). With your parameter settings above, `mutscan` will expect that the start of the provided WT sequence aligns with the first base in the reads.

**Second issue**
Not quite sure what is happening here. The warning appears since you are essentially specifying the output filename twice (the function will use the `outFile` as the output file, so if you want the output to go to `PATHNAME/results/QCresults_S1-S5.html`, please specify this in the `outFile` argument and remove the `output_file` argument). 
Since you say that the report generation is working with the test SE object, it may be an issue with `aa_collapse02` (rather than a JupyterLab issue). How did you create this object? You could perhaps try to run the code in the QC report manually (see code chunks in https://github.com/fmicompbio/mutscan/blob/master/inst/templates/qc_report_template.Rmd) to see why it fails.

**Comment by shesanIsland** [comment]
Hiya,

I've received the primer seq. for the amplicons and included the following using `digestFastqs ` but all reads are filtered out (even when only stating just part of the primer):

```
...
elementsForward = "PV",
elementLengthsForward = c(33,-1),
elementsReverse = "PV",
elementLengthsReverse = c(34-1),
primerForward = "TATAAGAGACAGTATAAGAGACAGTCAGTTTTT",      #dummy primer1
primerReverse = "TATAAGAGACAGTATAAGAGACAGTCAGTTTTTA",     #dummy primer2
...

```

I am unsure of the read composition but have been told the amplicons (and sometimes primers) can vary in length, especially after trimming (I assume a list could be used to bypass this issue ie `c(primerF1, primerF2, primerF3)` though I'm unsure about the `element` args). After pre-filtering and trimming using another tool, the primer sequences aren't found in all samples.

Best,

**Comment by csoneson** [comment]
Hi,

do you have single-end or paired-end data (from your previous post it seemed like single-end, but in this call you are specifying arguments for both forward and reverse reads)? 

A first step to figure out what happens would be to look at the `filterSummary` of your `digestFastqs()` output - that will tell you why reads are filtered out. 

Regarding the lengths, it is fine if they vary between reads, as long as you can assume that for each read, you will see the specified primer sequence, directly followed by the variable region (with your specification above). If multiple primers are possible, you can provide a vector to `primerForward` or `primerReverse`, as appropriate - in principle this should work also for primers of different lengths, if the remaining element lengths are -1 (in this case just choose one of the primer lengths for the primer element length). If only the end of the primer may be included, only specify the part that you are certain should be there (`mutscan` will look for perfect matches to the specified sequence).

**Comment by shesanIsland** [comment]
No, it is paired-end data but have been trimmed and merged with another tool before being passed as a "single read" in `digestFastqs()` (ie S1_R1 and S1_R2 is S1_merged). This tool was used instead simply to keep it consistent with previous pre-processing practices.

Apologies, I wasn't clear, I meant once adding the primer seq, all reads were removed at the primer filter stage, I hadn't realised it _completely excludes_ reads without an _exact_ match.

For future use,  since we cannot be sure each read will contain the entire primer seq, and they cannot guarantee the start of all reads in all samples start the same as the WTref, I assume it is fine to simply use `digestFastqs()` without primers and WTref to solely read and obtain the output metrics without further filtering/ digesting?

Wout the WTref, I assume I won't be able to identify single or double mutations, or the mutation-type in their dataset?

Thanks,

**Comment by csoneson** [comment]
> I assume it is fine to simply use digestFastqs() without primers and WTref to solely read and obtain the output metrics without further filtering/ digesting?

Sure - in this case you can apply the general filtering criteria, and you will get an output table with the count for each observed sequence. `mutscan` will not compare these to any WT reference, so you would need to identify the parts of the reads that correspond to the WT (and infer the mutations) in another way. The reason `mutscan` currently requires the WT and variable sequences to start in the same place is that if we're not observing, say, the first 3 nt of the sequence of interest, we also don't know if there would be an additional mutation there compared to the expected reference (so an identified single mutant would really be a double mutant, just that we didn't observe it).

**Comment by shesanIsland** [comment]
Thank you very much for taking the time to explain, this has been helpful!
